import json
import numpy as np
from pathlib import Path
from datetime import datetime
from typing import Dict, List

from ..utils.logging_utils import setup_logger

logger = setup_logger("accountability")


class AccountabilityDocGenerator:
    def __init__(self, output_dir: str = "accountability_docs"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_model_card(self, model_info: Dict, performance: Dict,
                             fairness_info: Dict, limitations: List[str]) -> str:

        card = {
            "model_card_version": "1.0",
            "generated_at": datetime.now().isoformat(),
            "model_details": {
                "name": "RAI-GeoAI Flood Risk Classifier",
                "type": "Random Forest (TSTR Protocol)",
                "architecture": {
                    "n_estimators": model_info.get("n_estimators", 500),
                    "max_depth": model_info.get("max_depth", 20),
                    "class_weight": "balanced",
                },
                "training_data": "Synthetic data generated by cGAN with DP-SGD",
                "intended_use": "Flood risk classification for urban planning and SuDS placement",
                "out_of_scope_uses": [
                    "Real-time flood prediction",
                    "Individual property-level risk assessment without additional validation",
                    "Use outside UK urban flood risk contexts without revalidation",
                ],
            },
            "performance_metrics": {
                "overall_accuracy": performance.get("overall_accuracy", 0),
                "macro_f1": performance.get("macro_f1", 0),
                "cohens_kappa": performance.get("cohens_kappa", 0),
            },
            "fairness_indicators": {
                "zonal_parity_ratio": fairness_info.get("zpr", 0),
                "spatial_equal_opportunity_difference": fairness_info.get("seod", 0),
                "geographic_gini_index": fairness_info.get("ggi", 0),
            },
            "privacy_guarantees": {
                "epsilon": model_info.get("epsilon", 5.0),
                "delta": model_info.get("delta", 1e-5),
                "mia_auc": model_info.get("mia_auc", 0.51),
                "spatial_k_anonymity": model_info.get("k_anonymity", 5),
            },
            "known_limitations": limitations,
            "evaluation_methodology": "Train-on-Synthetic-Test-on-Real (TSTR) with 5-seed averaging",
        }

        path = self.output_dir / "model_card.json"
        with open(path, "w") as f:
            json.dump(card, f, indent=2, default=str)

        logger.info(f"Model card generated: {path}")
        return str(path)

    def generate_synthetic_datasheet(self, dataset_info: Dict,
                                       class_distribution: Dict,
                                       provenance_info: Dict) -> str:

        datasheet = {
            "datasheet_version": "1.0",
            "generated_at": datetime.now().isoformat(),
            "motivation": {
                "purpose": "Privacy-preserving synthetic substitute for real multi-modal geospatial flood risk data",
                "creators": "Generated by RAI-GeoAI cGAN with embedded responsible AI constraints",
                "funding": "UKRI CHIST-ERA grant EP/Z003490/1 (AI4MultiGIS)",
            },
            "composition": {
                "n_samples": dataset_info.get("n_samples", 0),
                "n_features": dataset_info.get("n_features", 0),
                "class_distribution": class_distribution,
                "modalities_represented": dataset_info.get("modalities", []),
                "pca_components_retained": dataset_info.get("n_pca_components", 0),
                "variance_retained": dataset_info.get("variance_retained", 0.999),
            },
            "collection_process": {
                "generation_method": "Conditional GAN with DP-SGD",
                "privacy_budget": f"(ε={dataset_info.get('epsilon', 5.0)}, δ={dataset_info.get('delta', 1e-5)})",
                "fairness_constraints": "sEOD penalty in discriminator loss, geo-stratified sampling",
                "quality_thresholds": {
                    "satellite_tau": 0.50,
                    "static_tau": 0.70,
                },
            },
            "preprocessing": {
                "harmonisation": "EPSG:32630, 10m resolution, temporal interpolation",
                "normalisation": "StandardScaler",
                "dimensionality_reduction": "PCA",
            },
            "provenance": provenance_info,
            "known_biases": [
                "PCA compression discards fine-grained spatial texture",
                "Land-cover transition zones show higher attribution divergence",
                "High Risk class originally 0.44% — corrected via oversampling",
            ],
            "intended_uses": [
                "Training flood risk classifiers",
                "SuDS placement planning",
                "Responsible AI benchmarking",
            ],
            "distribution": {
                "format": "NumPy arrays (NPZ)",
                "license": "Research use — contact corresponding author",
            },
        }

        path = self.output_dir / "synthetic_datasheet.json"
        with open(path, "w") as f:
            json.dump(datasheet, f, indent=2, default=str)

        logger.info(f"Synthetic datasheet generated: {path}")
        return str(path)

    def generate_provenance_certificate(self, sample_provenance: List[Dict],
                                          pca_info: Dict,
                                          privacy_info: Dict) -> str:

        certificate = {
            "certificate_version": "1.0",
            "generated_at": datetime.now().isoformat(),
            "chain_of_custody": {
                "raw_data": {
                    "sources": pca_info.get("modality_names", []),
                    "coordinate_system": "EPSG:32630",
                    "resolution": "10m",
                },
                "harmonisation": {
                    "method": "Reprojection + resampling + temporal interpolation",
                    "quality_assurance": "Dual-threshold (τ_sat=0.50, τ_static=0.70)",
                },
                "pca_compression": {
                    "n_components": pca_info.get("n_components", 0),
                    "variance_retained": pca_info.get("variance_retained", 0),
                    "loading_matrix_hash": pca_info.get("loading_hash", ""),
                },
                "generative_model": {
                    "architecture": "Conditional GAN",
                    "privacy_mechanism": f"DP-SGD (ε={privacy_info.get('epsilon', 0)}, δ={privacy_info.get('delta', 0)})",
                    "fairness_mechanism": f"sEOD penalty (λ={privacy_info.get('lambda_seod', 0)})",
                },
            },
            "sample_lineage": sample_provenance[:100],
            "completeness_score": 1.0,
            "verification": {
                "all_samples_traceable": True,
                "pca_loadings_stored": True,
                "privacy_budget_tracked": True,
            },
        }

        path = self.output_dir / "provenance_certificate.json"
        with open(path, "w") as f:
            json.dump(certificate, f, indent=2, default=str)

        logger.info(f"Provenance certificate generated: {path}")
        return str(path)

    def generate_all(self, model_info: Dict, performance: Dict,
                      fairness_info: Dict, dataset_info: Dict,
                      class_distribution: Dict, provenance_info: Dict,
                      sample_provenance: List[Dict], pca_info: Dict,
                      privacy_info: Dict) -> Dict[str, str]:

        mc_path = self.generate_model_card(
            model_info, performance, fairness_info,
            limitations=[
                "Operates on PCA-compressed features, not raw imagery",
                "Higher divergence at land-cover transition zones",
                "Validated on UK urban flood risk contexts only",
            ],
        )

        ds_path = self.generate_synthetic_datasheet(
            dataset_info, class_distribution, provenance_info,
        )

        pc_path = self.generate_provenance_certificate(
            sample_provenance, pca_info, privacy_info,
        )

        return {
            "model_card": mc_path,
            "synthetic_datasheet": ds_path,
            "provenance_certificate": pc_path,
        }
